# This is a basic workflow to help you get started with Actions

name: GitHub Actions Task Bot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  schedule:
  # 定时任务，在每天的5点执行采集操作
    - cron: '0 21 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout codes'
        uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: bash ./shell.sh http://vhost680.0070.xyz/api.php/timming/index.html?enforce=1&name=%E7%99%BE%E5%BA%A6%E8%A7%86%E9%A2%91

